## =====================================================================
##  02_power_continuous.R
##
##  Size-adjusted power of B_n against its competitors, on the ten
##  continuous dependence schemes of Section 6 of the Supplementary
##  Material, at n = 50, 100, 200.
##
##  METHOD.  For each cell (scheme, noise level, sample size) the critical
##  value of every statistic is obtained from R0 null datasets generated by
##  drawing from the scheme and then permuting Y.  That null has exactly the
##  marginals the alternative has, which is what the per-replicate
##  permutation of the earlier study was buying; doing it once per cell
##  instead of once per replicate replaces R1 * B statistic evaluations by
##  R0 + R1.  Power is then the proportion of R1 independent draws from the
##  alternative whose statistic exceeds that critical value.
##
##  CONSEQUENCE, and the reason this script computes STATISTICS and never
##  calls a package's own test function: letting each package run its own
##  B = 1000 resampling costs roughly 3,100 single-core hours for Genest
##  alone over the three sample sizes.  Statistics only, the whole study is
##  about 10 hours on eight cores.
##
##  TUNING.  The primary study applies rule (12) uniformly, p = q =
##  max(1, floor(n^0.31) - 1), which gives 2, 3, 4 at n = 50, 100, 200.  The
##  earlier protocol set q = 1 for the five functional schemes, which uses
##  knowledge of the data-generating mechanism that the competitors are not
##  given; that variant is still run, as SECONDARY, and must be reported as
##  requiring prior knowledge that the dependence is a location relation.
##  Proposition 1 of the paper explains why it works: if the direction is
##  g = f (x) b_1 then all coefficients with j >= 2 vanish, so q = 1 captures
##  the whole noncentrality and saves p(q-1) degrees of freedom.
##
##  REPRODUCIBILITY.  Every cell is self-contained and seeds itself from
##  (n, scheme, noise), so results do not depend on the number of cores and
##  cells can be re-run individually.  Within a cell all tests see identical
##  data, both for calibration and for evaluation, so differences between
##  tests are not blurred by simulation noise.
## =====================================================================

library(dependence)
library(parallel)

## ---------------------------- configuration --------------------------
N_GRID  <- c(50L, 100L, 200L)
NU      <- seq(0.1, 2.0, by = 0.1)
ALPHA   <- 0.05
R0      <- 1e4              # null datasets per cell, for the critical value
R1      <- 1e4              # alternative datasets per cell
USE_MIC <- TRUE             # maximal information coefficient; in the current
                            # Table 2 of the paper, so on by default
SECONDARY_Q1 <- TRUE        # also run q = 1 on the five functional schemes
SEED    <- 20260810L
NCORES  <- max(1L, detectCores() - 1L)
OUTSTEM <- "power_continuous"

p_rule <- function(n) max(1L, as.integer(floor(n^0.31)) - 1L)
FUNCTIONAL <- c("linear", "quadratic", "cubic", "sine", "fourth root")

## --------------------------- the ten schemes -------------------------
## Second argument of N(0, v) in the paper is a VARIANCE, so sd = sqrt(v).
gen <- list(
  "linear"      = function(n, nu) { x <- runif(n); list(x = x, y = x + nu*rnorm(n)) },
  "quadratic"   = function(n, nu) { x <- runif(n); list(x = x, y = 4*(x-0.5)^2 + nu*rnorm(n)) },
  "cubic"       = function(n, nu) { x <- runif(n); z <- x - 1/3
                                    list(x = x, y = 128*z^3 - 48*z^2 - 12*z + nu*rnorm(n, 0, 3)) },
  "sine"        = function(n, nu) { x <- runif(n); list(x = x, y = sin(4*pi*x) + nu*rnorm(n, 0, 2)) },
  "fourth root" = function(n, nu) { x <- runif(n); list(x = x, y = x^0.25 + nu*rnorm(n, 0, 0.5)) },
  "circle"      = function(n, nu) { x <- runif(n); r <- rbinom(n, 1, 0.5)
                                    list(x = x, y = (2*r-1)*sqrt(pmax(0, 1-(2*x-1)^2)) + nu*rnorm(n, 0, 0.5)) },
  "two curves"  = function(n, nu) { x <- runif(n); r <- rbinom(n, 1, 0.5)
                                    list(x = x, y = 2*r*x + 0.5*(1-r)*sqrt(x) + nu*rnorm(n)) },
  "X"           = function(n, nu) { x <- runif(n); r <- rbinom(n, 1, 0.5)
                                    list(x = x, y = r*x + (1-r)*(1-x) + nu*rnorm(n, 0, 0.2)) },
  "diamond"     = function(n, nu) { x <- runif(n)
                                    y <- ifelse(x < 0.5, runif(n, 0.5-x, 0.5+x),
                                                         runif(n, x-0.5, 1.5-x))
                                    list(x = x, y = y + nu*rnorm(n, 0, 0.1)) },
  "heteroscedastic" = function(n, nu) { x <- abs(rnorm(n))          # chi with 1 df
                                    list(x = x, y = rnorm(n)*x + nu*rnorm(n)) }
)
stopifnot(length(gen) == 10L)

## ------------------------- statistic adapters ------------------------
## Each returns ONE number, larger meaning more dependence, and must not do
## any resampling of its own.
##
## VERIFY BEFORE THE FULL RUN.  The three marked below are the ones whose
## package interfaces are built around returning a test rather than a
## statistic; check each against the corresponding *.test() function on a
## single dataset and confirm the p-values agree.  If a statistic cannot be
## extracted, fall back to calibrating on that package's p-value instead:
## under H0 the p-value is uniform, so the same quantile trick applies, at
## the cost of granularity from a small B.
make_stats <- function() {
  s <- list(
    B_n = function(x, y, p, q) indeptest(x, y, p = p, q = q, basis = "poly",
                                         test = "Bartlett", ties = "first")$B_stat,
    P_n = function(x, y, p, q) indeptest(x, y, p = p, q = q, basis = "poly",
                                         test = "Pillai",   ties = "first")$P_stat,
    Hoeffding = function(x, y, p, q) Hmisc::hoeffd(cbind(x, y))$D[1, 2],
    dCov = function(x, y, p, q) energy::dcor(x, y),                     ## VERIFY
    HHG  = function(x, y, p, q) {                                       ## VERIFY
      Dx <- as.matrix(dist(x)); Dy <- as.matrix(dist(y))
      HHG::hhg.test(Dx, Dy, nr.perm = 0L)$sum.chisq
    },
    ## The Cramer-von Mises statistic of Genest, Neslehova and Remillard.
    ## B = 0 does NOT work: with an empty bootstrap array the package fails
    ## internally at t(xic) %*% M0.  The statistic is invariant to B --
    ## verified identical to seven figures at B = 2, 5 and 20 -- so the
    ## smallest workable B suffices and the bootstrap is pure overhead.
    ## $stat is a list, so the accessor is $stat$Sn and not $stat["Sn"].
    ## In the bivariate case with trunc.level = 2 there is a single subset,
    ## so cvm and Sn coincide, as do Tn and Tn2; this is the same degeneracy
    ## noted in Section 9 of the Supplementary Material.
    Genest = function(x, y, p, q)
      MixedIndTests::TestIndCopula(cbind(x, y), B = 2)$stat$Sn
  )
  if (USE_MIC)
    s$MIC <- function(x, y, p, q) minerva::mine_stat(x, y, measure = "mic")
  s
}

## Run every adapter once and report which work.  Any that fail are dropped
## with a warning rather than killing the run, since a broken interface to
## one competitor should not cost the whole study.  Each must return a
## single finite number.
self_test <- function(n = 50L, p = 2L, q = 2L, verbose = TRUE) {
  set.seed(1); x <- runif(n); y <- x + 0.5*rnorm(n)
  S <- make_stats(); ok <- logical(length(S)); names(ok) <- names(S)
  for (nm in names(S)) {
    t0 <- Sys.time()
    v <- tryCatch(as.numeric(S[[nm]](x, y, p, q)), error = function(e) e)
    dt <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
    bad <- inherits(v, "error") || length(v) != 1L || !is.finite(v)
    ok[nm] <- !bad
    if (verbose) message(sprintf("  %-10s %s", nm,
      if (inherits(v, "error")) paste("FAILED:", conditionMessage(v))
      else if (bad) sprintf("FAILED: returned length %d, value %s", length(v),
                            paste(format(v), collapse = ","))
      else sprintf("ok  %-12.6g  (%.3f s)", v, dt)))
  }
  ok
}

## Fallbacks, if an adapter above cannot be made to yield a statistic.
##
##  dCov    energy::dcor(x, y) needs x, y as columns; try as.matrix(x).
##          energy::dcov(x, y) is an alternative, but is not scale-free, so
##          use dcor for comparability across schemes.
##  HHG     if nr.perm = 0 is rejected, use nr.perm = 1 and take $sum.chisq,
##          which is the observed statistic and does not depend on the
##          single permutation drawn.
##  Genest  resolved: B = 2 with the public interface, see the adapter.  A
##          faster route exists, the unexported MixedIndTests:::Sn_A(x, 2),
##          whose $Sn element is the same statistic computed without any
##          bootstrap; note it needs trunc.level explicitly, having no
##          default.  It is not used here because the bootstrap at B = 2 is
##          already too cheap to measure and ::: reaches into a private
##          namespace that can change without notice.  If the timing check
##          at n = 200 shows otherwise, switch, and first confirm that
##            MixedIndTests:::Sn_A(cbind(x, y), 2)$Sn
##          reproduces the value TestIndCopula reports on the same data.
##  Any     as a last resort, calibrate on the package's p-value instead of
##          its statistic: under H0 the p-value is uniform, so the same
##          quantile trick applies, with granularity 1/(B+1).  Wrap as
##          function(x, y, p, q) -pkg::something.test(x, y, B = 199)$p.value
##          and note the sign, since the script assumes larger means more
##          dependence.

## ------------------------------ one cell -----------------------------
## Returns power and the calibrated critical value for every statistic.
run_cell <- function(cell) {
  library(dependence)
  S <- make_stats(); nm <- names(S)
  n <- cell$n; nu <- cell$nu; sch <- cell$scheme; p <- cell$p; q <- cell$q
  set.seed(SEED + 1009L*which(N_GRID == n) + 7919L*cell$si +
             104729L*as.integer(round(nu*10)) + 13L*cell$q)
  g <- gen[[sch]]
  ev <- function(d) vapply(S, function(f) as.numeric(f(d$x, d$y, p, q)), 0)

  null <- matrix(NA_real_, R0, length(S), dimnames = list(NULL, nm))
  for (i in seq_len(R0)) {                       # same marginals, independent
    d <- g(n, nu); d$y <- sample(d$y); null[i, ] <- ev(d)
  }
  crit <- apply(null, 2L, quantile, probs = 1 - ALPHA, names = FALSE, type = 7)

  alt <- matrix(NA_real_, R1, length(S), dimnames = list(NULL, nm))
  for (i in seq_len(R1)) alt[i, ] <- ev(g(n, nu))

  pw <- colMeans(sweep(alt, 2L, crit, ">"))
  data.frame(n = n, scheme = sch, nu = nu, p = p, q = q, test = nm,
             power = as.numeric(pw),
             se = sqrt(as.numeric(pw) * (1 - as.numeric(pw)) / R1),
             crit = as.numeric(crit), R0 = R0, R1 = R1,
             row.names = NULL, stringsAsFactors = FALSE)
}

## ------------------------------- driver ------------------------------
cells <- list()
for (n in N_GRID) for (si in seq_along(gen)) for (nu in NU) {
  sch <- names(gen)[si]
  cells[[length(cells) + 1L]] <-
    list(n = n, si = si, scheme = sch, nu = nu, p = p_rule(n), q = p_rule(n))
  if (SECONDARY_Q1 && sch %in% FUNCTIONAL)
    cells[[length(cells) + 1L]] <-
      list(n = n, si = si, scheme = sch, nu = nu, p = p_rule(n), q = 1L)
}
message(sprintf("%d cells | R0 = %g, R1 = %g | orders %s | %d cores",
                length(cells), R0, R1,
                paste(sprintf("n=%d:p=%d", N_GRID, vapply(N_GRID, p_rule, 0L)),
                      collapse = " "), NCORES))

## Check every adapter before committing to the grid, and drop any that the
## installed package versions will not yield a statistic for.
message("adapter self-test:")
STAT_OK <- self_test(n = N_GRID[1], p = p_rule(N_GRID[1]), q = p_rule(N_GRID[1]))
if (!all(STAT_OK)) {
  warning("dropping adapters that failed: ",
          paste(names(STAT_OK)[!STAT_OK], collapse = ", "),
          ". See the fallbacks documented above make_stats().")
  .keep <- names(STAT_OK)[STAT_OK]
  make_stats <- local({ f <- make_stats; k <- .keep
                        function() f()[k] })
}
stopifnot("B_n must be available" = "B_n" %in% names(make_stats()))

## A single cell first, as a smoke test and to time the whole run.
t0 <- Sys.time(); probe <- run_cell(cells[[1]])
dt <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
message(sprintf("one cell at n=%d took %.1f s; whole study approx %.1f h on %d cores",
                cells[[1]]$n, dt, dt*length(cells)/3600/NCORES, NCORES))
print(probe)

cl <- makeCluster(NCORES)
clusterExport(cl, c("gen", "make_stats", "run_cell", "N_GRID", "R0", "R1",
                    "ALPHA", "SEED", "USE_MIC", "p_rule", "FUNCTIONAL",
                    "self_test", "STAT_OK"))
invisible(clusterEvalQ(cl, {library(dependence); library(parallel)}))
res <- do.call(rbind, parLapplyLB(cl, cells, run_cell))
stopCluster(cl)
write.csv(res, paste0(OUTSTEM, ".csv"), row.names = FALSE)

## --------------------------- checks and summary ----------------------
prim <- res[res$q == res$p, ]                      # primary study

## The rank statistics are distribution-free, so their calibrated critical
## values should not vary across schemes or noise levels.  This is a free
## internal check on the whole calibration step.
for (tst in intersect(c("B_n", "P_n", "Hoeffding"), unique(prim$test)))
  for (n in N_GRID) {
    v <- prim$crit[prim$test == tst & prim$n == n]
    message(sprintf("  distribution-free check: %-10s n=%-4d crit range %.4g .. %.4g (rel. spread %.1e)",
                    tst, n, min(v), max(v), diff(range(v))/mean(v)))
  }

summ <- do.call(rbind, lapply(split(prim, list(prim$n, prim$test), drop = TRUE),
  function(d) data.frame(n = d$n[1], test = d$test[1],
                         mean_power = mean(d$power), sd_power = sd(d$power))))
rk <- do.call(rbind, lapply(split(prim, list(prim$n, prim$scheme, prim$nu), drop = TRUE),
  function(d) data.frame(n = d$n[1], test = d$test, rank = rank(-d$power, ties.method = "average"))))
summ$mean_rank <- vapply(seq_len(nrow(summ)), function(i)
  mean(rk$rank[rk$n == summ$n[i] & rk$test == summ$test[i]]), 0)
summ <- summ[order(summ$n, summ$mean_rank), ]
print(summ, row.names = FALSE)
write.csv(summ, paste0(OUTSTEM, "_summary.csv"), row.names = FALSE)

## LaTeX fragment for the main paper
fmt <- function(v) sub("0\\.", "0{\\\\cdot}", sprintf("%.3f", v))
con <- file(paste0(OUTSTEM, "_summary.tex"), open = "wt")
writeLines(c("\\begin{table}",
"\\tbl{Size-adjusted empirical power across ten dependence schemes and twenty noise levels}{%",
"\\begin{tabular}{l rrr rrr rrr}", "\\hline",
paste0(" & ", paste(sprintf("\\multicolumn{3}{c}{$n = %d$}", N_GRID), collapse = " & "), " \\\\"),
paste0("Test & ", paste(rep("Mean & SD & Rank", length(N_GRID)), collapse = " & "), " \\\\"),
"\\hline",
vapply(unique(summ$test[summ$n == N_GRID[1]]), function(t) {
  cells <- vapply(N_GRID, function(n) { d <- summ[summ$n == n & summ$test == t, ]
    sprintf("$%s$ & $%s$ & $%s$", fmt(d$mean_power), fmt(d$sd_power), fmt(d$mean_rank)) }, "")
  sprintf("%s & %s \\\\", t, paste(cells, collapse = " & ")) }, ""),
"\\hline", "\\end{tabular}}",
"\\begin{tabnote}",
sprintf("Critical values are size-adjusted within each combination of scheme, noise level and sample size, from $%g$ null datasets obtained by permuting $Y$; power is over $%g$ independent draws from the alternative, so the largest standard error is $%s$. Orders follow rule (12), giving $p=q=%s$. The mean rank is the average rank, with one the best, within each combination.",
        R0, R1, fmt(0.5/sqrt(R1)),
        paste(vapply(N_GRID, p_rule, 0L), collapse = ", ")),
"\\end{tabnote}", "\\label{tab:power_summary}", "\\end{table}"), con)
close(con)
message("\nWritten: ", OUTSTEM, ".csv, ", OUTSTEM, "_summary.csv, ", OUTSTEM, "_summary.tex")
