# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Discrete Chebyshev (Gram) polynomial basis
#'
#' Computes the orthonormal polynomial basis on the grid
#' {1/(n+1), 2/(n+1), ..., n/(n+1)} using the three-term
#' recurrence. Returns an n x p matrix U such that
#' (1/n) * t(U) %*% U = I_p exactly.
#' Cost: O(n*p) time, O(n*p) space.
#' No QR, no Vandermonde matrix needed.
#'
#' @param n positive integer with the number of points n
#' @param p positive integer with the degree of the polynomial
#'
#' @returns A \eqn{n \times p} matrix with the basis vectors.
#' @export
chebyshev_basis <- function(n, p) {
    .Call('_dependence_chebyshev_basis', PACKAGE = 'dependence', n, p)
}

#' Quick QR on after de-meaning
#'
#' It computes the QR decomposition of a matrix B
#' after substracting the means of the columns of B.
#' It is much quicker than \code{qr.Q(qr(M))}.
#'
#' @param B matrix to be de-meaned and decomposed
#'
#' @returns The Q matrix of the decomposition.
quick_qr <- function(B) {
    .Call('_dependence_quick_qr', PACKAGE = 'dependence', B)
}

